### ISSUE TITLE
any plans to replicate B-LoRA for Stable Diffusion 3 Medium model?

### ISSUE THREAD

**Issue by biswaroop1547** [yardenfren1996/B-LoRA#13]
Hi just want to check if you have any plans to replicate your work for Stable Diffusion 3 medium model? since going forward I think SD3 would replace most of its predecessors.

It's been a great experience so far in using B-LoRA for SDXL :)

**Comment by liusida** [comment]
+1

**Comment by yardenfren1996** [comment]
Since B-LoRA relies on the inherent separation within the blocks of SDXL, it is necessary to check whether the same separation exists in SD3. Unfortunately, I am not currently familiar with the architecture of SD3, but it sounds like an interesting test. I encourage you to explore whether such separations exist (You might find even more interesting separations such as material and human identity) which could eventually allow for more control in the generation process.

In case I will try this, I will notify you here.

Thank you.
